import type { Department, ThesisCategory, Thesis } from "@/types/api";

export const ACADEMIC_DEPARTMENTS: Department[] = [
  {
    id: "d1",
    name: "Computer Science & Artificial Intelligence",
    code: "CSAI",
    institution: { id: "i2", name: "Massachusetts Institute of Technology" },
    created_at: "2024-01-15T08:00:00Z",
    updated_at: "2025-05-14T10:00:00Z",
    description: "Distributed architectures, scalable foundation models, algorithmic theory, and edge neural processing.",
    thesesCount: 48,
    totalViews: 42180,
    topics: ["Neural Compilation", "Edge Transformers", "Formal Verification"],
    topThesis: {
      id: "t1",
      title: "Scalable Transformer Inference on Resource-Constrained Edge Devices",
      author: "Aisha Rahman",
      views: 4821,
    },
  },
  {
    id: "d2",
    name: "Electrical Engineering & Robotics",
    code: "EE",
    institution: { id: "i2", name: "Massachusetts Institute of Technology" },
    created_at: "2024-01-15T08:00:00Z",
    updated_at: "2024-12-15T10:00:00Z",
    description: "Neuromorphic silicon, ultra-low-power integrated circuits, and bio-inspired robotic control mechanisms.",
    thesesCount: 36,
    totalViews: 31450,
    topics: ["Neuromorphic Silicon", "Power Microgrids", "Mixed-Signal VLSI"],
    topThesis: {
      id: "t4",
      title: "Neuromorphic Spiking Circuits for Low-Power Robotic Control",
      author: "Kenji Sato",
      views: 3654,
    },
  },
  {
    id: "d3",
    name: "Applied Physics & Photonics",
    code: "APP",
    institution: { id: "i3", name: "ETH Zürich" },
    created_at: "2024-02-01T08:00:00Z",
    updated_at: "2025-03-20T10:00:00Z",
    description: "Topological quantum states, optical dielectric resonators, and semiconductor backscattering suppression.",
    thesesCount: 32,
    totalViews: 28910,
    topics: ["Topological Photonics", "Surface Codes", "Dielectric Waveguides"],
    topThesis: {
      id: "t2",
      title: "Topological Edge States in Two-Dimensional Photonic Crystals",
      author: "Marco Bianchi",
      views: 2974,
    },
  },
  {
    id: "d4",
    name: "School of Computing & Data Science",
    code: "SOC",
    institution: { id: "i4", name: "National University of Singapore" },
    created_at: "2024-02-10T08:00:00Z",
    updated_at: "2025-06-30T10:00:00Z",
    description: "Privacy-preserving federated intelligence, clinical machine learning, and large-scale graph networks.",
    thesesCount: 41,
    totalViews: 35620,
    topics: ["Federated Aggregation", "Non-IID Clinical AI", "Drug Discovery GNNs"],
    topThesis: {
      id: "t3",
      title: "Federated Learning Under Non-IID Clinical Data Distributions",
      author: "Priya Nair",
      views: 3180,
    },
  },
  {
    id: "d5",
    name: "Computer Laboratory & Systems",
    code: "CL",
    institution: { id: "i1", name: "University of Cambridge" },
    created_at: "2024-01-20T08:00:00Z",
    updated_at: "2025-07-18T10:00:00Z",
    description: "Resilient consensus protocols, verifiable computation, differential privacy, and microkernel security.",
    thesesCount: 29,
    totalViews: 24700,
    topics: ["Byzantine Fault Tolerance", "Confidential Compute", "Differential Privacy"],
    topThesis: {
      id: "t5",
      title: "Differentially Private Fine-Tuning of Large Language Models",
      author: "Elena Costa",
      views: 2540,
    },
  },
  {
    id: "d6",
    name: "Quantum Information & Physics",
    code: "PHY",
    institution: { id: "i1", name: "University of Cambridge" },
    created_at: "2024-03-01T08:00:00Z",
    updated_at: "2025-04-12T10:00:00Z",
    description: "Fault-tolerant quantum error correction, surface code decoders, and topological material simulation.",
    thesesCount: 26,
    totalViews: 22890,
    topics: ["Surface-Code Decoders", "Quantum Annealing", "Topological Materials"],
    topThesis: {
      id: "t6",
      title: "Optimised Decoding for Surface-Code Quantum Error Correction",
      author: "Tom Becker",
      views: 2210,
    },
  },
  {
    id: "d7",
    name: "Biomedical Informatics & Chemical Sciences",
    code: "BME",
    institution: { id: "i4", name: "National University of Singapore" },
    created_at: "2024-03-15T08:00:00Z",
    updated_at: "2025-08-01T10:00:00Z",
    description: "De novo molecular generation, protein ligand binding simulations, and spatial transcriptomic models.",
    thesesCount: 34,
    totalViews: 29140,
    topics: ["Molecular GNNs", "Protein Folding Models", "Target Docking"],
    topThesis: {
      id: "t7",
      title: "Graph Neural Networks for De Novo Drug Discovery",
      author: "Sofia Rossi",
      views: 2890,
    },
  },
  {
    id: "d8",
    name: "Energy Systems & Sustainable Engineering",
    code: "ESE",
    institution: { id: "i5", name: "University of Tokyo" },
    created_at: "2024-04-01T08:00:00Z",
    updated_at: "2025-01-10T10:00:00Z",
    description: "Decentralized model-predictive controls, islanded microgrids, and high-penetration renewable dispatch.",
    thesesCount: 24,
    totalViews: 19820,
    topics: ["Islanded Microgrids", "Dynamic Frequency Stabilization", "Predictive Grid Dispatch"],
    topThesis: {
      id: "t8",
      title: "Resilient Microgrid Control Under High Renewable Penetration",
      author: "James O'Connor",
      views: 1890,
    },
  },
];

export const ACADEMIC_CATEGORIES: ThesisCategory[] = [
  {
    id: "c2",
    name: "Artificial Intelligence & Machine Learning",
    slug: "artificial-intelligence-machine-learning",
    description: "Foundation models, reinforcement learning, edge acceleration, and neural optimization architectures.",
    visits: 28450,
    thesesCount: 42,
    featuredTopic: "Transformer Optimization & Distillation",
    created_at: "2024-01-10T08:00:00Z",
    updated_at: "2025-08-15T10:00:00Z",
  },
  {
    id: "c3",
    name: "Electrical & Neuromorphic Engineering",
    slug: "electrical-neuromorphic-engineering",
    description: "Bio-inspired silicon circuits, ultra-low power edge signal processing, and robotics controls.",
    visits: 21900,
    thesesCount: 35,
    featuredTopic: "Spiking Neural Hardware",
    created_at: "2024-01-10T08:00:00Z",
    updated_at: "2025-08-15T10:00:00Z",
  },
  {
    id: "c8",
    name: "Photonics & Optical Quantum Physics",
    slug: "photonics-optical-quantum-physics",
    description: "Topological edge states, laser cavities, photonic integrated circuits, and light-matter interfaces.",
    visits: 18320,
    thesesCount: 29,
    featuredTopic: "Dielectric Photonic Waveguides",
    created_at: "2024-01-10T08:00:00Z",
    updated_at: "2025-08-15T10:00:00Z",
  },
  {
    id: "c1",
    name: "Distributed Computing & Network Systems",
    slug: "distributed-computing-network-systems",
    description: "Decentralized consensus, high-throughput cloud storage, and fault-tolerant multi-agent architectures.",
    visits: 16400,
    thesesCount: 31,
    featuredTopic: "Consensus Under Network Partitioning",
    created_at: "2024-01-10T08:00:00Z",
    updated_at: "2025-08-15T10:00:00Z",
  },
  {
    id: "c7",
    name: "Quantum Computing & Information Theory",
    slug: "quantum-computing-information-theory",
    description: "Surface code error mitigation, quantum algorithm complexity, and tensor network simulations.",
    visits: 14750,
    thesesCount: 24,
    featuredTopic: "Belief-Propagation Decoders",
    created_at: "2024-01-10T08:00:00Z",
    updated_at: "2025-08-15T10:00:00Z",
  },
  {
    id: "c5",
    name: "Renewable Energy & Microgrid Systems",
    slug: "renewable-energy-microgrid-systems",
    description: "Decentralized smart grids, solar-hydrogen conversion, and grid-scale dynamic storage management.",
    visits: 12890,
    thesesCount: 22,
    featuredTopic: "Model Predictive Frequency Stabilization",
    created_at: "2024-01-10T08:00:00Z",
    updated_at: "2025-08-15T10:00:00Z",
  },
  {
    id: "c9",
    name: "Computational Biology & Genomics",
    slug: "computational-biology-genomics",
    description: "Molecular structure generative modeling, clinical trial analytics, and genetic variant classification.",
    visits: 11200,
    thesesCount: 19,
    featuredTopic: "Deep De Novo Molecular Design",
    created_at: "2024-01-10T08:00:00Z",
    updated_at: "2025-08-15T10:00:00Z",
  },
  {
    id: "c4",
    name: "Mechanical & Structural Engineering",
    slug: "mechanical-structural-engineering",
    description: "Additive manufacturing metallurgy, continuum damage mechanics, and structural aeroelasticity.",
    visits: 9800,
    thesesCount: 16,
    featuredTopic: "Fatigue Life Under Thermal Transients",
    created_at: "2024-01-10T08:00:00Z",
    updated_at: "2025-08-15T10:00:00Z",
  },
];

export const ACADEMIC_THESES: Thesis[] = [
  {
    id: "t1",
    title: "Scalable Transformer Inference on Resource-Constrained Edge Devices",
    abstract:
      "This thesis investigates efficient inference architectures for large transformer models deployed on edge hardware with limited memory and compute budgets. We propose a hybrid quantisation-aware distillation pipeline that reduces parameter footprint by 63% while preserving within 1.4% of the teacher model's accuracy across GLUE and SuperGLUE benchmarks. The work contributes a runtime scheduler that adapts batch sizing to thermal envelopes and demonstrates real-time viability on ARM Cortex-A class devices.",
    author_name: "Aisha Rahman",
    supervisor_name: "Prof. David Karger",
    publication_date: "2025-05-14",
    status: "published",
    created_at: "2025-04-02T10:00:00Z",
    institution: { id: "i2", name: "Massachusetts Institute of Technology" },
    department: { id: "d1", name: "Computer Science & Artificial Intelligence" },
    category: { id: "c2", name: "Artificial Intelligence & Machine Learning" },
    tags: ["transformers", "edge computing", "model distillation", "quantisation", "inference"],
    fileUrl: "https://drive.google.com/file/d/sample-t1",
    year: 2025,
    language: "English",
    page_count: 142,
    view_count: 4821,
    download_count: 1310,
    citation_count: 38,
  },
  {
    id: "t4",
    title: "Neuromorphic Spiking Circuits for Low-Power Robotic Control",
    abstract:
      "This work maps a proportional-derivative control policy onto a mixed-signal spiking neural network fabricated in 65nm CMOS, achieving sub-milliwatt trajectory tracking on a quadruped platform. In-memory analogue synapses reduce dynamic switching energy by 88% over equivalent digital DSP implementations while exhibiting robustness to thermal drift.",
    author_name: "Kenji Sato",
    supervisor_name: "Prof. Maria López",
    publication_date: "2024-11-08",
    status: "published",
    created_at: "2024-09-15T10:00:00Z",
    institution: { id: "i2", name: "Massachusetts Institute of Technology" },
    department: { id: "d2", name: "Electrical Engineering & Robotics" },
    category: { id: "c3", name: "Electrical & Neuromorphic Engineering" },
    tags: ["neuromorphic", "spiking neural networks", "robotics", "low-power", "mixed-signal"],
    fileUrl: "https://drive.google.com/file/d/sample-t4",
    year: 2024,
    language: "English",
    page_count: 168,
    view_count: 3654,
    download_count: 921,
    citation_count: 27,
  },
  {
    id: "t3",
    title: "Federated Learning Under Non-IID Clinical Data Distributions",
    abstract:
      "A framework for training diagnostic models across hospital silos without centralising sensitive patient data. We introduce a variance-controlled aggregation scheme that mitigates client drift under severe non-IID conditions and validate its convergence rate on multi-site cardiology datasets with stringent privacy guarantees.",
    author_name: "Priya Nair",
    supervisor_name: "Prof. Olivia Chen",
    publication_date: "2025-06-30",
    status: "published",
    created_at: "2025-06-01T10:00:00Z",
    institution: { id: "i4", name: "National University of Singapore" },
    department: { id: "d4", name: "School of Computing & Data Science" },
    category: { id: "c2", name: "Artificial Intelligence & Machine Learning" },
    tags: ["federated learning", "privacy", "clinical AI", "non-iid", "variance reduction"],
    fileUrl: "https://drive.google.com/file/d/sample-t3",
    year: 2025,
    language: "English",
    page_count: 135,
    view_count: 3180,
    download_count: 742,
    citation_count: 22,
  },
  {
    id: "t2",
    title: "Topological Edge States in Two-Dimensional Photonic Crystals",
    abstract:
      "We examine the robustness of topologically protected edge modes in dielectric photonic crystals under fabrication disorder. Through finite-element simulation and a bespoke tight-binding model, we characterise the band topology via Zak phases and demonstrate backscattering-suppressed waveguiding at telecom wavelengths.",
    author_name: "Marco Bianchi",
    supervisor_name: "Prof. Hannah Schmidt",
    publication_date: "2025-02-20",
    status: "published",
    created_at: "2025-01-10T10:00:00Z",
    institution: { id: "i3", name: "ETH Zürich" },
    department: { id: "d3", name: "Applied Physics & Photonics" },
    category: { id: "c8", name: "Photonics & Optical Quantum Physics" },
    tags: ["photonics", "topology", "edge states", "optics", "dielectrics"],
    fileUrl: "https://drive.google.com/file/d/sample-t2",
    year: 2025,
    language: "English",
    page_count: 120,
    view_count: 2974,
    download_count: 642,
    citation_count: 31,
  },
  {
    id: "t7",
    title: "Graph Neural Networks for De Novo Drug Discovery",
    abstract:
      "A scaffold-aware graph neural network that generates novel druglike molecules with designated target binding affinity. Validated against the DUD-E benchmark and in silico molecular docking suites, the method demonstrates an 18% improvement in synthetic accessibility score over baseline variational autoencoders.",
    author_name: "Sofia Rossi",
    supervisor_name: "Prof. Olivia Chen",
    publication_date: "2025-04-18",
    status: "published",
    created_at: "2025-03-01T10:00:00Z",
    institution: { id: "i4", name: "National University of Singapore" },
    department: { id: "d7", name: "Biomedical Informatics & Chemical Sciences" },
    category: { id: "c9", name: "Computational Biology & Genomics" },
    tags: ["GNN", "drug discovery", "cheminformatics", "docking", "molecular generation"],
    fileUrl: "https://drive.google.com/file/d/sample-t7",
    year: 2025,
    language: "English",
    page_count: 154,
    view_count: 2890,
    download_count: 580,
    citation_count: 19,
  },
  {
    id: "t5",
    title: "Differentially Private Fine-Tuning of Large Language Models",
    abstract:
      "We analyse the privacy-utility trade-off when applying DP-SGD to instruction tuning of 7B-parameter models, and propose gradient clipping schedules that recover most of the non-private baseline quality at epsilon=4 while bounding client extraction probability.",
    author_name: "Elena Costa",
    supervisor_name: "Prof. David Karger",
    publication_date: "2025-07-18",
    status: "published",
    created_at: "2025-07-02T10:00:00Z",
    institution: { id: "i1", name: "University of Cambridge" },
    department: { id: "d5", name: "Computer Laboratory & Systems" },
    category: { id: "c1", name: "Distributed Computing & Network Systems" },
    tags: ["differential privacy", "LLM", "fine-tuning", "DP-SGD", "privacy budget"],
    fileUrl: "https://drive.google.com/file/d/sample-t5",
    year: 2025,
    language: "English",
    page_count: 128,
    view_count: 2540,
    download_count: 412,
    citation_count: 15,
  },
  {
    id: "t6",
    title: "Optimised Decoding for Surface-Code Quantum Error Correction",
    abstract:
      "A neural belief-propagation decoder that reduces logical error rates by an order of magnitude compared to minimum-weight matching at realistic circuit noise levels. FPGA implementations achieve microsecond-scale decoding cycles required for fault-tolerant quantum logic gates.",
    author_name: "Tom Becker",
    supervisor_name: "Prof. Hannah Schmidt",
    publication_date: "2025-03-05",
    status: "published",
    created_at: "2025-01-20T10:00:00Z",
    institution: { id: "i1", name: "University of Cambridge" },
    department: { id: "d6", name: "Quantum Information & Physics" },
    category: { id: "c7", name: "Quantum Computing & Information Theory" },
    tags: ["quantum computing", "error correction", "surface codes", "neural decoders"],
    fileUrl: "https://drive.google.com/file/d/sample-t6",
    year: 2025,
    language: "English",
    page_count: 145,
    view_count: 2210,
    download_count: 405,
    citation_count: 24,
  },
  {
    id: "t8",
    title: "Resilient Microgrid Control Under High Renewable Penetration",
    abstract:
      "We propose a distributed model-predictive controller that maintains frequency stability in islanded microgrids with 80%+ renewable penetration. Rigorous hardware-in-the-loop experiments confirm sub-cycle transient containment during generation shedding events.",
    author_name: "James O'Connor",
    supervisor_name: "Prof. Maria López",
    publication_date: "2024-12-12",
    status: "published",
    created_at: "2024-10-01T10:00:00Z",
    institution: { id: "i5", name: "University of Tokyo" },
    department: { id: "d8", name: "Energy Systems & Sustainable Engineering" },
    category: { id: "c5", name: "Renewable Energy & Microgrid Systems" },
    tags: ["microgrids", "renewables", "control systems", "frequency stability", "model predictive control"],
    fileUrl: "https://drive.google.com/file/d/sample-t8",
    year: 2024,
    language: "English",
    page_count: 138,
    view_count: 1890,
    download_count: 333,
    citation_count: 18,
  },
];

export const TOTAL_STATS = {
  totalPublished: ACADEMIC_THESES.length,
  institutions: 5,
  departments: ACADEMIC_DEPARTMENTS.length,
  totalViews: ACADEMIC_DEPARTMENTS.reduce((sum, d) => sum + (d.totalViews || 0), 0),
  totalDownloads: ACADEMIC_THESES.reduce((sum, t) => sum + (t.download_count || 0), 0),
};
