/**
 * Mock dataset backing the API service layer during frontend development.
 * Replace by pointing the domain modules at the real Django endpoints.
 */

export const institutions = [
  {
    id: "i1",
    name: "University of Cambridge",
    code: "UCAM",
    country: "United Kingdom",
    website: "https://cam.ac.uk",
    active: true,
  },
  {
    id: "i2",
    name: "Massachusetts Institute of Technology",
    code: "MIT",
    country: "United States",
    website: "https://mit.edu",
    active: true,
  },
  {
    id: "i3",
    name: "ETH Zürich",
    code: "ETHZ",
    country: "Switzerland",
    website: "https://ethz.ch",
    active: true,
  },
  {
    id: "i4",
    name: "National University of Singapore",
    code: "NUS",
    country: "Singapore",
    website: "https://nus.edu.sg",
    active: true,
  },
  {
    id: "i5",
    name: "University of Tokyo",
    code: "UTOKYO",
    country: "Japan",
    website: "https://u-tokyo.ac.jp",
    active: false,
  },
];

export const departments = [
  {
    id: "d1",
    name: "Computer Science & Artificial Intelligence",
    code: "CSAI",
    institutionId: "i2",
    driveFolderLink: "https://drive.google.com/drive/folders/mit-csai",
    active: true,
  },
  {
    id: "d2",
    name: "Electrical Engineering",
    code: "EE",
    institutionId: "i2",
    driveFolderLink: "https://drive.google.com/drive/folders/mit-ee",
    active: true,
  },
  {
    id: "d3",
    name: "Engineering",
    code: "ENG",
    institutionId: "i3",
    driveFolderLink: "",
    active: true,
  },
  {
    id: "d4",
    name: "Computer Laboratory",
    code: "CL",
    institutionId: "i1",
    driveFolderLink: "",
    active: true,
  },
  {
    id: "d5",
    name: "School of Computing",
    code: "SOC",
    institutionId: "i4",
    driveFolderLink: "",
    active: true,
  },
  {
    id: "d6",
    name: "Physics",
    code: "PHY",
    institutionId: "i1",
    driveFolderLink: "",
    active: true,
  },
];

export const categories = [
  {
    id: "c1",
    name: "Computer Science",
    slug: "computer-science",
    parentId: null,
  },
  {
    id: "c2",
    name: "Artificial Intelligence",
    slug: "artificial-intelligence",
    parentId: "c1",
  },
  {
    id: "c3",
    name: "Machine Learning",
    slug: "machine-learning",
    parentId: "c2",
  },
  { id: "c4", name: "Engineering", slug: "engineering", parentId: null },
  {
    id: "c5",
    name: "Electrical Engineering",
    slug: "electrical-engineering",
    parentId: "c4",
  },
  {
    id: "c6",
    name: "Natural Sciences",
    slug: "natural-sciences",
    parentId: null,
  },
  { id: "c7", name: "Physics", slug: "physics", parentId: "c6" },
  {
    id: "c8",
    name: "Applied Physics",
    slug: "applied-physics",
    parentId: "c7",
  },
];

const DRIVE =
  "https://drive.google.com/file/d/1AbCdEfGhIjKlMnOpQrStUvWxYz/view";

export const theses = [
  {
    id: "t1",
    slug: "scalable-transformer-inference-edge-devices",
    title:
      "Scalable Transformer Inference on Resource-Constrained Edge Devices",
    abstract:
      "This thesis investigates efficient inference architectures for large transformer models deployed on edge hardware with limited memory and compute budgets. We propose a hybrid quantisation-aware distillation pipeline that reduces parameter footprint by 63% while preserving within 1.4% of the teacher model's accuracy across GLUE and SuperGLUE benchmarks. The work contributes a runtime scheduler that adapts batch sizing to thermal envelopes and demonstrates real-time viability on ARM Cortex-A class devices.",
    keywords: [
      "transformers",
      "edge computing",
      "model distillation",
      "quantisation",
      "inference",
    ],
    author: "Aisha Rahman",
    supervisor: "Prof. David Karger",
    coSupervisors: ["Dr. Lena Vogt"],
    institutionId: "i2",
    departmentId: "d1",
    categoryId: "c3",
    publicationDate: "2025-05-14",
    status: "published",
    fileUrl: DRIVE,
    views: 4821,
    downloads: 1310,
    createdDate: "2025-04-02",
    updatedDate: "2025-05-14",
  },
  {
    id: "t2",
    slug: "photonic-crystals-topological-edge-states",
    title: "Topological Edge States in Two-Dimensional Photonic Crystals",
    abstract:
      "We examine the robustness of topologically protected edge modes in dielectric photonic crystals under fabrication disorder. Through finite-element simulation and a bespoke tight-binding model, we characterise the band topology via Zak phases and demonstrate backscattering-suppressed waveguiding at telecom wavelengths.",
    keywords: ["photonics", "topology", "edge states", "optics"],
    author: "Marco Bianchi",
    supervisor: "Prof. Hannah Schmidt",
    coSupervisors: [],
    institutionId: "i3",
    departmentId: "d3",
    categoryId: "c8",
    publicationDate: "2025-02-20",
    status: "published",
    fileUrl: DRIVE,
    views: 2974,
    downloads: 642,
    createdDate: "2025-01-10",
    updatedDate: "2025-02-20",
  },
  {
    id: "t3",
    slug: "federated-learning-non-iid-clinical-data",
    title: "Federated Learning Under Non-IID Clinical Data Distributions",
    abstract:
      "A framework for training diagnostic models across hospital silos without centralising patient data. We introduce a variance-controlled aggregation scheme that mitigates client drift under severe non-IID conditions and validate on multi-site cardiology datasets.",
    keywords: ["federated learning", "privacy", "clinical AI", "non-iid"],
    author: "Priya Nair",
    supervisor: "Prof. Olivia Chen",
    coSupervisors: ["Dr. Samuel Okafor"],
    institutionId: "i4",
    departmentId: "d5",
    categoryId: "c3",
    publicationDate: "2025-06-30",
    status: "under_review",
    fileUrl: DRIVE,
    views: 1180,
    downloads: 88,
    createdDate: "2025-06-01",
    updatedDate: "2025-06-30",
  },
  {
    id: "t4",
    slug: "neuromorphic-spiking-circuits-robotics",
    title: "Neuromorphic Spiking Circuits for Low-Power Robotic Control",
    abstract:
      "This work maps a proportional-derential control policy onto a mixed-signal spiking neural network fabricated in 65nm, achieving sub-milliwatt trajectory tracking on a quadruped platform.",
    keywords: [
      "neuromorphic",
      "spiking neural networks",
      "robotics",
      "low-power",
    ],
    author: "Kenji Sato",
    supervisor: "Prof. Maria López",
    coSupervisors: [],
    institutionId: "i5",
    departmentId: "d2",
    categoryId: "c5",
    publicationDate: "2024-11-08",
    status: "published",
    fileUrl: DRIVE,
    views: 3654,
    downloads: 921,
    createdDate: "2024-09-15",
    updatedDate: "2024-11-08",
  },
  {
    id: "t5",
    slug: "differential-privacy-large-language-models",
    title: "Differentially Private Fine-Tuning of Large Language Models",
    abstract:
      "We analyse the privacy-utility trade-off when applying DP-SGD to instruction tuning of 7B-parameter models, and propose gradient clipping schedules that recover most of the non-private baseline quality at epsilon=4.",
    keywords: ["differential privacy", "LLM", "fine-tuning", "DP-SGD"],
    author: "Elena Costa",
    supervisor: "Prof. David Karger",
    coSupervisors: ["Dr. Lena Vogt"],
    institutionId: "i2",
    departmentId: "d1",
    categoryId: "c3",
    publicationDate: "2025-07-18",
    status: "submitted",
    fileUrl: DRIVE,
    views: 540,
    downloads: 12,
    createdDate: "2025-07-02",
    updatedDate: "2025-07-18",
  },
  {
    id: "t6",
    slug: "quantum-error-correction-surface-codes",
    title: "Optimised Decoding for Surface-Code Quantum Error Correction",
    abstract:
      "A neural belief-propagation decoder that reduces logical error rates by an order of magnitude compared to minimum-weight matching at realistic circuit noise levels.",
    keywords: ["quantum computing", "error correction", "surface codes"],
    author: "Tom Becker",
    supervisor: "Prof. Hannah Schmidt",
    coSupervisors: [],
    institutionId: "i3",
    departmentId: "d3",
    categoryId: "c7",
    publicationDate: "2025-03-05",
    status: "approved",
    fileUrl: DRIVE,
    views: 2210,
    downloads: 405,
    createdDate: "2025-01-20",
    updatedDate: "2025-03-05",
  },
  {
    id: "t7",
    slug: "graph-neural-networks-drug-discovery",
    title: "Graph Neural Networks for De Novo Drug Discovery",
    abstract:
      "A scaffold-aware GNN that generates novel molecules with target binding affinity, validated against DUD-E and in silico docking.",
    keywords: ["GNN", "drug discovery", "cheminformatics"],
    author: "Sofia Rossi",
    supervisor: "Prof. Olivia Chen",
    coSupervisors: ["Dr. Samuel Okafor"],
    institutionId: "i4",
    departmentId: "d5",
    categoryId: "c2",
    publicationDate: "2025-08-01",
    status: "draft",
    fileUrl: "",
    views: 0,
    downloads: 0,
    createdDate: "2025-08-01",
    updatedDate: "2025-08-01",
  },
  {
    id: "t8",
    slug: "resilient-microgrids-renewable-integration",
    title: "Resilient Microgrid Control Under High Renewable Penetration",
    abstract:
      "We propose a distributed model-predictive controller that maintains frequency stability in islanded microgrids with 80%+ renewable share.",
    keywords: ["microgrids", "renewables", "control systems"],
    author: "James O'Connor",
    supervisor: "Prof. Maria López",
    coSupervisors: [],
    institutionId: "i5",
    departmentId: "d2",
    categoryId: "c5",
    publicationDate: "2024-12-12",
    status: "published",
    fileUrl: DRIVE,
    views: 1890,
    downloads: 333,
    createdDate: "2024-10-01",
    updatedDate: "2024-12-12",
  },
];

export function institutionName(id) {
  return institutions.find((i) => i.id === id)?.name ?? "—";
}
export function departmentName(id) {
  return departments.find((d) => d.id === id)?.name ?? "—";
}
export function categoryName(id) {
  return categories.find((c) => c.id === id)?.name ?? "—";
}
